name: Snyk Security Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Snyk
        run: npm install -g snyk
      
      - name: Verificar archivos del directorio
        run: ls -la
      
      # Analizar código y ENVIAR resultados a Snyk
      - name: Run Snyk Code to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --sarif-file-output=snyk-code.sarif || true
      
      # IMPORTANTE: Monitor para enviar a Snyk Dashboard
      - name: Upload results to Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --project-name=dvwa-activity
        continue-on-error: true
      
      # Subir resultados a GitHub Security
      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif
        if: always()
      
      - name: Run Snyk to check Docker
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -f "Dockerfile" ]; then
            snyk container test $(docker build -q .) || true
          fi
        continue-on-error: true
